Verdictd dev 4
alibaba/inclavare-containers pull request #1247
Opened 2021-07-29 06:21 UTC by liangzhou121

Add wrapKey and unwrapKey grpc service which will be used by ocicrypto and AA.

2021-08-01 09:43 UTC, jiazhang0 requested changes

2021-08-01 09:43 UTC, jiazhang0 commented on verdictd/app/src/key_provider/key_provider_grpc.rs
> +//use core::slice::SlicePattern;
remove the comment line

2021-08-01 09:43 UTC, jiazhang0 commented on verdictd/app/src/key_provider/key_provider_grpc.rs
> +        //get kid
Add a space between `//` and the first character. Please fix all these issues.

2021-08-02 02:19 UTC, voidC1326 approved these changes

2021-08-02 02:37 UTC, voidC1326 approved these changes

2021-08-02 02:43 UTC, merged