EAA: add verdictd's design doc
alibaba/inclavare-containers pull request #1495
Opened 2021-11-24 06:47 UTC by liangzhou121

Signed-off-by: Zhou Liang <liang.a.zhou@linux.alibaba.com>

2021-11-24 06:53 UTC, jialez0 approved these changes

2021-11-24 07:12 UTC, haosanzi commented on eaa/verdictd/docs/design/design.md
> +
should pass

2021-11-24 07:12 UTC, haosanzi commented on eaa/verdictd/docs/design/design.md
> +These complex problems can be resloved by HW-TEE's remote attestation technologies. But remote attestation's mechanism and deployment are complicated to general customers.
resloved ---> resolved

2021-11-24 07:12 UTC, haosanzi commented on eaa/verdictd/docs/design/design.md
> +Enclave Attestation Architecture(EAA) Verdictd was built to simple the deployment of remote attestation procedure. It integrates these different platforms' remote attestations into general service.
simple is adjective , change simple  to simplify

2021-11-24 07:12 UTC, haosanzi commented on eaa/verdictd/docs/design/design.md
> +- Verdictd will execute following inspections after receive evidence from AA:
receiving

2021-11-24 07:12 UTC, haosanzi commented on eaa/verdictd/docs/design/design.md
> +In order to maximum Verdictd's scalability, all functionalities were implemented as separately static RUST modules. Each module can be added or excluded during compiling stage.
maximize

2021-11-24 07:13 UTC, haosanzi commented
Please use Grammarly to perform grammar and vocabulary checks

2021-11-27 06:23 UTC, liangzhou121 commented
> 

Yes, I checked these new contents with Grammarly tool according to your suggestion.

2021-11-28 01:46 UTC, jiazhang0 requested changes

2021-11-28 01:46 UTC, jiazhang0 commented on eaa/verdictd/docs/design/design.md
> +# Introduction
Add an empty line.

2021-11-28 01:46 UTC, jiazhang0 commented on eaa/verdictd/docs/design/design.md
> +HW-TEE-based cloud security solutions provide a higher level of protection as compared to software-only security measures.
Add an empty line.

2021-11-29 02:01 UTC, haosanzi approved these changes

2021-12-03 01:11 UTC, merged