rune/libenclave/skeleton && sgx-tools: Solve the launch token adaptat…
alibaba/inclavare-containers pull request #156
Opened 2020-09-08 02:28 UTC by haosanzi

…ion problem of sgx2 + in-tree

- sgx-tools gen-token command reports an error when running on FLC machines
- Operations related to lanunch token are not supported on FLC machines

Signed-off-by: Shirong Hao shirong@linux.alibaba.com

2020-09-08 02:37 UTC, jiazhang0 requested changes

2020-09-08 02:37 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/skeleton/Makefile
> +IS_OOT_DRIVER ?= $(shell if [ -e /dev/isgx ]; then echo "1"; else echo "0"; fi;)
IS_OOT_DRIVER is not used anywhere. Delete it plz.

2020-09-08 02:37 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/skeleton/Makefile
> +    HOST_CFLAGS += -DDEBUG_ENCLAVE
Why enclave must be debug if flc is unavailable?

2020-09-08 02:37 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
> +#ifdef DEBUG_ENCLAVE
This is not right way. The detection of the necessity of launch token **MUST** be dynamic. You change the flexibility in a static way. Plz remove DEBUG_ENCLAVE.

2020-09-08 02:37 UTC, jiazhang0 commented on sgx-tools/gen-token.go
> +		if intelsgx.IsSGXLaunchControlSupported() {
So you did well here with a runtime detection but why applying a static form in skeleton?

2020-09-08 09:24 UTC, jiazhang0 requested changes

2020-09-08 09:24 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/skeleton/sgxutils.c
> +	return false;
Change to:
```C
return !!(cpu_info[2] & 0x40000000);
```

2020-09-08 09:59 UTC, YangLiang3 reviewed
1.  In Makefile 
$(OUTPUT)/encl.token: $(OUTPUT)/encl.ss
            sgx-tools gen-token --signature encl.ss --token $

2020-09-08 09:59 UTC, YangLiang3 commented on rune/libenclave/internal/runtime/pal/skeleton/Makefile
> +ifeq ($(IS_SGX_FLC),0)
It's better to add below in Makefile
ifeq ($(IS_SGX_FLC),0)
$(OUTPUT)/encl.token: $(OUTPUT)/encl.ss
          sgx-tools gen-token --signature encl.ss --token $@
endif

2020-09-08 09:59 UTC, YangLiang3 commented on rune/libenclave/internal/runtime/pal/skeleton/sgx.h
> +
The format issue.  Please use tab intead of space.

2020-09-08 10:25 UTC, YangLiang3 commented on rune/libenclave/internal/runtime/pal/skeleton/Makefile
> +ifeq ($(IS_SGX_FLC),0)
$(OUTPUT)/liberpal-skeleton*.o \
$(OUTPUT)/liberpal-skeleton*.so \
$(OUTPUT)/signing_key.pem \
ifeq ($(IS_SGX_FLC),0)
$(OUTPUT)/encl.token 
endif

ifeq ($(IS_SGX_FLC),0)
        EXTRA_CLEAN += $(OUTPUT)/encl.token
endif

2020-09-08 10:27 UTC, YangLiang3 commented on rune/libenclave/internal/runtime/pal/skeleton/Makefile
it's better to add  as below in Makefile
ifeq ($(IS_SGX_FLC),0)
$(OUTPUT)/encl.token: $(OUTPUT)/encl.ss
        sgx-tools gen-token --signature encl.ss --token $@
endif

ifeq ($(IS_SGX_FLC),0)
EXTRA_CLEAN += $(OUTPUT)/encl.token
endif

2020-09-08 10:27 UTC, YangLiang3 commented on rune/libenclave/internal/runtime/pal/skeleton/Makefile
it's better to add as below in Makefile
ifeq ($(IS_SGX_FLC),0)
$(OUTPUT)/encl.token: $(OUTPUT)/encl.ss
sgx-tools gen-token --signature encl.ss --token $@
endif

ifeq ($(IS_SGX_FLC),0)
EXTRA_CLEAN += $(OUTPUT)/encl.token
endif

2020-09-08 11:31 UTC, jiazhang0 commented on sgx-tools/gen-token.go
> +			return fmt.Errorf("It is not suitable to run the sgx-tools gen-token command on flc machines")
Change to:
```
"gen-token command is unable to run without SGX launch control feature"
```

2020-09-09 02:00 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/skeleton/Makefile
> +        $(OUTPUT)/encl.token: $(OUTPUT)/encl.ss
This indent is not necessary for rule.

2020-09-09 04:44 UTC, jiazhang0 approved these changes

2020-09-09 04:45 UTC, merged