README: document a `Deployment` section instead of `Running`
alibaba/inclavare-containers pull request #242
Opened 2020-10-28 12:50 UTC by haosanzi

Fixes: #241

Signed-off-by: Shirong Hao <shirong@linux.alibaba.com>

2020-10-28 13:12 UTC, jiazhang0 commented
Still need changes to clarify what the differences are between containerd and dockerd integration. @haosanzi

2020-10-28 14:05 UTC, hustliyilin commented on README.md
> +- Inclavare Containers integrated with containerd can be deployed on Confidential Computing Kubernetes Cluster scenarios. Because `shim-rune` and `rune` can compose a basic enclave containerization s
Attentation your spelling please, you should use `container image doesn't` or `container images don't`, You should check grammars before committing your code.

2020-10-28 14:09 UTC, hustliyilin commented on README.md
> +- Inclavare Containers integrated with containerd can be deployed on Confidential Computing Kubernetes Cluster scenarios. Because `shim-rune` and `rune` can compose a basic enclave containerization s
You can use [grammarly](https://www.grammarly.com/) to check your spelling before committing your docs.

2020-10-28 15:33 UTC, jiazhang0 requested changes

2020-10-28 15:33 UTC, jiazhang0 commented on README.md
> +- Inclavare Containers integrated with dockerd can be deployed on docker scenarios, you need to install enclave image into container image so that various enclave runtimes can be launched by `rune` t
Change to:

```
The former targets using docker to deploy Inclavare Containers. Specifically, you need to install the preferred enclave runtime when building container image, and then launch the enclave runtime through `rune` and [enclave runtime specific PAL](docs/design/terminology.md#enclave-runtime-pal).
```

2020-10-28 15:33 UTC, jiazhang0 commented on README.md
> +- Inclavare Containers integrated with containerd can be deployed on Confidential Computing Kubernetes Cluster scenarios. Because `shim-rune` and `rune` can compose a basic enclave containerization s
Chang to:

```
The latter targets using K8s to deploy Inclavare Containers. In this scenario, `shim-rune` and `rune` can compose an enclave containerization stack, so enclave runtime is not required and installed when building container image,  providing with the same experience as ordinary containers.
```

2020-10-28 15:33 UTC, jiazhang0 commented on README.md
> +**Note that we don't provide any reference images containing enclave runtime.**
Change to:

```
All reference container images don't contain enclave runtime. They are only used for the deployment with containerd.
```

2020-10-29 01:54 UTC, hustliyilin reviewed
It’s best not to use ``` in the commit title and body.

2020-10-29 03:40 UTC, hustliyilin approved these changes

2020-10-29 10:50 UTC, merged