rune pal - Add a base support for aws sample nitro enclave
alibaba/inclavare-containers pull request #350
Opened 2020-11-28 03:45 UTC by Simon-aikuier

Implement a pal interface to support was nitro enclave.
For now just to run the sample enclave image file in EC2 instance.

2020-11-28 03:48 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/pal_ne.c
> +{
Change to:
```
{
  *enclave_fd = ioctl(ne_dev_fd, NE_CREATE_VM, slot_uid);
  if (*enclave_fd >= 0)
    return 0;

  // stuffs about *enclave_fd < 0
}
```

2020-11-28 03:53 UTC, jiazhang0 requested changes

2020-11-28 03:53 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/pal_ne.c
> +
remote this newline.

2020-11-28 03:53 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/pal_ne.c
> +
remote this newline.

2020-11-28 03:53 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/pal_ne.c
> +	ne_free_mem_regions(ne_user_mem_regions);
enclave_fd should be closed after ne_free_mem_regions(ne_user_mem_regions)

2020-11-28 03:53 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/pal_ne.c
> +	ne_free_mem_regions(ne_user_mem_regions);
ditto

2020-11-28 05:26 UTC, jiazhang0 requested changes

2020-11-28 06:53 UTC, haosanzi commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/README.md
> +refer to [Amazon EC2 instances](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Instances.html) to create a `EC2` instance which need to enable Enclave. Note that the limitation:
s/refer/Refer/.

2020-11-28 06:53 UTC, haosanzi commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/README.md
> +refer to [Getting started: Hello enclave](https://docs.aws.amazon.com/enclaves/latest/user/getting-started.html) to build a `nitro enclave` environment in parent instance.
s/refer/Refer/.

2020-11-29 17:18 UTC, jiazhang0 requested changes

2020-11-29 17:18 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/ne.c
> +	int rc = -EINVAL;
Why still leaving this line?

2020-11-29 17:18 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/ne.c
> +	rc = *enclave_fd;
Why returning enclave fd instead of -EINVAL?

2020-11-29 17:21 UTC, jiazhang0 commented
Closed. Review new pr https://github.com/alibaba/inclavare-containers/pull/354

2020-11-29 17:21 UTC, closed without merging