rune/pal - Add a base support for aws sample nitro enclave in one commit
alibaba/inclavare-containers pull request #354
Opened 2020-11-29 15:02 UTC by Simon-aikuier

Implement a pal interface to support was nitro enclave.
For now just to run the sample enclave image file in EC2 instance.
All commits merge to one commit.

2020-11-29 17:22 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/ne.c
> +	int rc = -EINVAL;
Why not removing this line?

2020-11-29 17:22 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/ne.c
> +	rc = *enclave_fd;
returning encalve_fd not 0 or -EINVALD?

2020-11-29 17:24 UTC, jiazhang0 commented
@Simon-aikuier Please create the commit with `git commit -s` using your SOB. In addition, this pr is associated with this issue https://github.com/alibaba/inclavare-containers/issues/345. Please refer to this info https://github.com/alibaba/inclavare-containers/blob/master/CONTRIBUTING.md#commit-message to add a fix line.

2020-11-29 18:51 UTC, Simon-aikuier commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/ne.c
> +	int rc = -EINVAL;
done

2020-11-29 18:51 UTC, Simon-aikuier commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/ne.c
> +	rc = *enclave_fd;
done

2020-11-30 02:22 UTC, jiazhang0 requested changes

2020-11-30 02:22 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/README.md
> +## Build nitro enclave environment
Please add newline following all titles.

2020-11-30 02:22 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/README.md
> +
remove this empty line.

2020-11-30 02:22 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/pal_ne.c
> +	close(enclave_fd);
close enclave fd should be called after ne_free_mem_regions().

2020-11-30 02:22 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/pal_ne.c
> +	close(enclave_fd);
the fd and ne_user_mem_regions are allocated by pal_init, so the release operation should be executed in pal_destroy() instead of here.

2020-11-30 02:22 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/pal_ne.c
> +	//TODO: maybe also call close enclave_fd to release enclave instance
Change to:
```
// TODO: xxxx
```

2020-11-30 02:22 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/pal_ne.c
> +	// ne_free_mem_regions(ne_user_mem_regions);
remove these useless lines.

2020-11-30 02:22 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/nitro_enclaves/pal_ne.c
> +	printf("Enclave vCPUs were added\n");
Move ne_set_user_mem_region and  ne_add_vcpu to pal_init(). They belongs to the initialization phase.

2020-11-30 08:50 UTC, jiazhang0 commented
This PR is replaced by https://github.com/alibaba/inclavare-containers/pull/357.

2020-11-30 08:50 UTC, closed without merging