rune/libenclave: support new enclave type jailhouse
alibaba/inclavare-containers pull request #362
Opened 2020-12-02 09:26 UTC by hustliyilin

There are more and more non hardware-assisted enclave forms to support.
Jailhouse is one of this kind of enclave, we should support it.

Fixes:#344

Signed-off-by: Yilin Li <YiLin.Li@linux.alibaba.com>

2020-12-02 09:32 UTC, jiazhang0 requested changes

2020-12-02 09:32 UTC, jiazhang0 commented on rune/libenclave/configs/config.go
> +	EnclaveTypeJailHouse        string = "jailhouse"
rename to 'Jailhouse'.

2020-12-02 09:32 UTC, jiazhang0 commented on rune/libenclave/jailhouse/device_linux.go
> +	logrus.Debug("Jail House Enclaves detected")
Change to `Jailhouse Enclave detected`

2020-12-03 01:19 UTC, jiazhang0 approved these changes

2020-12-03 02:15 UTC, haosanzi approved these changes

2020-12-03 05:07 UTC, merged