rune/libenlave/skeleton: add xfrm and attribute metadate area
alibaba/inclavare-containers pull request #414
Opened 2020-12-14 03:22 UTC by haosanzi

Since the built environment and runtime environment may be different. It is necessary for users to defined the expected value of the processor extension state supported by the target platform at runtime by themselves. The expected value will be stored in the metadata area in enclave images, skeleton will act according.

Signed-off-by: Shirong Hao <shirong@linux.alibaba.com>

2020-12-14 03:30 UTC, jiazhang0 requested changes

2020-12-14 03:30 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
> +		{"attr", required_argument, NULL, 'a'},
Change to "attrs".

2020-12-14 03:30 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
> +			meta_data.xfrm = atoi(optarg);
Use strtol() to convert the input hex string to integer value instead. Typing a decimal number as input is counter-intuitive.

2020-12-14 03:30 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
> +			meta_data.attributes = atoi(optarg);
ditto

2020-12-14 04:19 UTC, jiazhang0 requested changes

2020-12-14 04:19 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
> +		ss.body.attributes = meta_data.attributes;
Change to:

```
#ifndef CONFIG_EINITTOKENKEY
	ss.body.attributes = SGX_ATTR_MODE64BIT;
#else
	ss.body.attributes = SGX_ATTR_MODE64BIT | SGX_ATTR_EINITTOKENKEY;
 #endif
 	if (enclave_debug)
 		ss.body.attributes |= SGX_ATTR_DEBUG;

if (meta_data.attributes) {
    /* ss.body.attributes is the minimum set of attributes to set */
    if (meta_data.attributes & ss.body.attributes != ss.body.attributes) {
        err_exit("...");
    }

    ss.body.attributes = meta_data.attributes;
}
```

2020-12-14 04:19 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
> +		ss.body.xfrm = meta_data.xfrm;
ditto.

2020-12-14 08:05 UTC, jiazhang0 requested changes

2020-12-14 08:05 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
> +	}
Move this chunk of attributes code ahead of generating xfrm.

2020-12-14 08:05 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
> +		secs->xfrm = meta_data->xfrm & secs->xfrm;
The xfrm from metadata area indicates the subjective requirement to enforce. So if any bit in xfrm from metadata is not available, an error should be raised.

```C
if (meta_data->xfrm) {
    if (secs->xfrm & meta_data->xfrm != meta_data->xfrm)
        err_exit("...");
}
```

2020-12-14 08:14 UTC, jiazhang0 commented
@haosanzi The max line length of commit header cannot exceed 80 characters.

2020-12-14 12:51 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
> +		/* Check attributes to prevent possible tampering of metadata area. */
Don't need to end up with a ".".

2020-12-14 13:03 UTC, jiazhang0 requested changes

2020-12-14 13:03 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
> +				secs->xfrm);
You need to report the unavailable bits claimed in meta_data->xfrm.

2020-12-14 13:26 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
> +				secs->xfrm);
Use `meta_data->xfrm & ~(secs->xfrm & meta_data->xfrm)` to get the mask of unavailable bits.

2020-12-15 02:56 UTC, jiazhang0 approved these changes

2020-12-15 03:20 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
> +	}
I think the minimal set can be set into metadata area:
```
} else {
    meta_data.attributes = ss.body.attributes;
}
```

2020-12-15 03:21 UTC, jiazhang0 commented on rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
> +	}
ditto.

2020-12-15 03:28 UTC, YangLiang3 approved these changes

2020-12-15 03:33 UTC, jiazhang0 requested changes
Still need to improve.

2020-12-15 06:17 UTC, jiazhang0 requested changes
Everything looks perfect except the commit header in a single line is too long.

2020-12-15 06:26 UTC, jiazhang0 approved these changes

2020-12-15 06:28 UTC, merged